[package]
name = "CommunicatorServer_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.3"
serde = "1.0.202"
serde_json = "1.0.117"
uuid = { version = "1.8.0", features = ["v4"] }
